---
name: Colloquy-Data
version: 1.15
author:
  - Nicola Worthington <nicolaw@cpan.org>
abstract: Read Colloquy 1.3 and 1.4 data files
license: open_source
requires:
  Carp: 0
  Safe: 2.11
recommends:
  Test: 0
  Test::Assertions: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Colloquy::Data:
    file: lib/Colloquy/Data.pm
    version: 1.15
generated_by: Module::Build version 0.2611
