# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Colloquy-Data
version:      1.14
version_from: lib/Colloquy/Data.pm
installdirs:  site
requires:
    Carp:                          0
    Test::Assertions:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
